# Basic Setup

In [3]:
import quandl
quandl.ApiConfig.api_key = "REMOVED"

# Reading in a table with some filters

In [9]:
# Just check the api for each dataset, this one takes multiple dates and tickers
quandl.get_table('DNB/SIRA', datepll='201104,201204,201304', ticker='PLRBQ,CBT')

,datepll,basecat,crating,orating,history,cond_ind,ob_ind,finance,moved,fire,...,doll_1201,doll_1801,doll_9991,dolloth1,dollnpm1,doll_pm1,businessname,ticker,isin,cusip6
None,,,,,,,,,,,,,,,,,,,,,
0,201104,R,None,GG3,P,None,0,R,0,0,...,0.0,0.0,0.0,0.0,35100.0,59300.0,"Plymouth Rubber Company, Inc.",PLRBQ,US7300262000,730026
1,201204,R,None,GG3,P,None,0,R,0,0,...,250.0,0.0,0.0,0.0,0.0,78000.0,"Plymouth Rubber Company, Inc.",PLRBQ,US7300262000,730026
2,201304,R,NQ,None,P,None,1,R,0,0,...,250.0,0.0,0.0,0.0,0.0,67650.0,"Plymouth Rubber Company, Inc.",PLRBQ,US7300262000,730026
3,201104,R,5A2,NQ,N,U,0,R,0,0,...,150250.0,2500.0,1425.0,20450.0,70550.0,13930600.0,Cabot Corporation,CBT,US1270551013,127055
4,201204,R,5A2,NQ,N,U,0,None,0,0,...,36000.0,375.0,0.0,23200.0,68450.0,18623000.0,Cabot Corporation,CBT,US1270551013,127055
5,201304,R,5A2,NQ,N,U,0,None,0,0,...,26625.0,19825.0,0.0,23200.0,67150.0,18096900.0,Cabot Corporation,CBT,US1270551013,127055